services:
  monaco:
    container_name: monaco
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL:-}
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      NODE_ENV: production
    restart: unless-stopped
